# fly.toml app configuration file generated for linkflare on 2024-05-08T10:10:07-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'linkflare'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PORT = '4321'
  NODE_ENV = 'production'
  
